<a href="https://colab.research.google.com/github/Jirawan1998/datascience_bootcamp_project/blob/main/Essential_Python_for_Data_Analyst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Contents**
- review class OOP
- review loop + dict
- try except
- assert
- csv, json, context manager
- web scraping
- numpy pandas sqlite sklearn

In [117]:
# super class
# OOP
class Person:
    def __init__(self, name):
        self.name = name
    def hey(self):
        print("hello world!")
    def sayhi(self):
        print(f"Hi my name is {self.name}")

class Employee(Person): #super class
    def __init__(self, name, company):
        super().__init__(name)
        self.company = company
    def potato(self):
        print("Potato is very good")
    def sayhi(self):
        print(f"Hi my name is {self.name} and I work at {self.company}.")

In [118]:
tuk = Person("Tuk")
tuk.sayhi()

Hi my name is Tuk


In [119]:
tuk = Person("Tuk")
john = Employee("John", "Google")
tuk.sayhi()
john.sayhi()

Hi my name is Tuk
Hi my name is John and I work at Google.


In [120]:
tuk.hey()
john.hey()

hello world!
hello world!


In [121]:
john.sayhi()
john.potato()

Hi my name is John and I work at Google.
Potato is very good


In [122]:
# try-except block
try:
    1/0
except:
    print("This is an error message")

This is an error message


In [123]:
try:
    print(y)
except ZeroDivisionError:
    print("Cannot divide a number with zero.")
except NameError:
    print("Variable is not found.")

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64


In [124]:
try:
    x = "hello"
    x = int(x)
except ZeroDivisionError:
    print("Cannot divide a number with zero.")
except NameError:
    print("Variable is not found.")
except ValueError:
    print("Please check your data type again")

Please check your data type again


In [125]:
try:
    print("haha")
except ZeroDivisionError:
    print("Cannot divide a number with zero.")
except NameError:
    print("Variable is not found.")
except ValueError:
    print("Please check your data type again")
else:
    print("Done")
finally:
    print("This is the last line")

haha
Done
This is the last line


In [126]:
assert 1+1 == 2, "1+1 must be equal 2"

In [127]:
def check_this(a,b):
    assert a+b > 10, "a+b should be more than 10"
    return a+b

In [128]:
check_this(10,20)

30

In [129]:
# lamda function

In [130]:
def greeting(name):
    print("hello!" + name)

In [131]:
greeting = lambda name:  print("hello!" + name)

In [132]:
greeting("tuk")

hello!tuk


In [133]:
def odd_or_even(num):
    if num % 2 == 0:
        print("Even")
    else:
        print("Odd")

In [134]:
odd_or_even = lambda num: "even" if num % 2 == 0 else "odd"

In [135]:
odd_or_even(5)

'odd'

In [136]:
odd_or_even(4)

'even'

In [137]:
hello = lambda : print("hello!")

In [138]:
hello()

hello!


In [139]:
# list of colored balls
# test
balls = ['red','red', 'green', 'blue', 'blue' ]

In [140]:
for ball in balls:
    print(ball)

red
red
green
blue
blue


In [141]:
result = {} # empty dict

for ball in balls:
    if ball in result:
        result[ball] += 1 # += 1 -> result[ball] + 1
    else:
        result[ball] = 1
print(result)

{'red': 2, 'green': 1, 'blue': 2}


In [142]:
def summary(list_items):
    result = {}
    for item in list_items:
        if item in result:
            result[item] += 1
        else: 
            result[item] = 1
    return(result)
    

In [143]:
summary(balls)

{'red': 2, 'green': 1, 'blue': 2}

In [144]:
# comma separated values (CSV file)


In [145]:
!pwd

/content


In [146]:
!ls

Hotel.csv	    newfile.csv       starwarapi.csv
hotel_modified.csv  newjsonfile.json  tuk.json
imdb_data.csv	    sample_data       value_hotel.csv


In [147]:
!ls sample_data

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [148]:
!mkdir newFolder

In [149]:
!rmdir newFolder

In [150]:
!echo hello

hello


In [151]:
!cat Hotel.csv

id,hotel,location,price
1,Accor,Thiland,50
2,Lbis,Italy,50
3,London,UK,35
4,Seoul,Korea,30
5,Le Concord,USA,25

In [152]:
import csv 

file = open("Hotel.csv")

data = csv.reader(file)

for row in data:
    print(row)

file.close()

['\ufeffid', 'hotel', 'location', 'price']
['1', 'Accor', 'Thiland', '50']
['2', 'Lbis', 'Italy', '50']
['3', 'London', 'UK', '35']
['4', 'Seoul', 'Korea', '30']
['5', 'Le Concord', 'USA', '25']


In [153]:
try:
    file = open("hotel.csv")
    data = csv.reader(file)
    file.close()
except FileNotFoundError:
    print("File Not Found")
else:
    print("Load dara successfully")



File Not Found


In [154]:
# context manager
import csv

with open("Hotel.csv", "r") as file:
    data = csv.reader(file)
    for row in data:
        print(row)


['\ufeffid', 'hotel', 'location', 'price']
['1', 'Accor', 'Thiland', '50']
['2', 'Lbis', 'Italy', '50']
['3', 'London', 'UK', '35']
['4', 'Seoul', 'Korea', '30']
['5', 'Le Concord', 'USA', '25']


In [155]:
# context manager & try-except block
import csv

try:
    with open("Hotel.csv", "r") as file:
        data = csv.reader(file)
        for row in data:
            print(row)
except:
    print("Found some errors, please check again")


['\ufeffid', 'hotel', 'location', 'price']
['1', 'Accor', 'Thiland', '50']
['2', 'Lbis', 'Italy', '50']
['3', 'London', 'UK', '35']
['4', 'Seoul', 'Korea', '30']
['5', 'Le Concord', 'USA', '25']


In [156]:
# context manager
csv_data = [] # empty list

with open("Hotel.csv", "r") as file:
        data = csv.reader(file)
        for row in data:
            csv_data.append(row)
print(csv_data)

[['\ufeffid', 'hotel', 'location', 'price'], ['1', 'Accor', 'Thiland', '50'], ['2', 'Lbis', 'Italy', '50'], ['3', 'London', 'UK', '35'], ['4', 'Seoul', 'Korea', '30'], ['5', 'Le Concord', 'USA', '25']]


In [157]:
# modern python
import pandas as pd
df = pd.read_csv("Hotel.csv") 
df["price_double"] = df["price"]*2
df.to_csv("hotel_modified.csv") 
df

id       hotel location  price  price_double
0   1       Accor  Thiland     50           100
1   2        Lbis    Italy     50           100
2   3      London       UK     35            70
3   4       Seoul    Korea     30            60
4   5  Le Concord      USA     25            50

In [158]:
# write csv file 
# "w" write mode
import csv

headers = ["id", "name", "age"]
data = [
    [1, "jisoo", 25],
    [2, "tuk", 24],
    [3, "john", 32]
]

with open("newfile.csv", "w") as file:
    writer = csv.writer(file)
    writer.writerow(headers)
    writer.writerows(data)


In [159]:
!cat newfile.csv

id,name,age
1,jisoo,25
2,tuk,24
3,john,32


In [160]:
result =[]
with open("newfile.csv", "r") as file:
    data = csv.reader(file)
    for row in data:
        result.append(row)
print(result)


[['id', 'name', 'age'], ['1', 'jisoo', '25'], ['2', 'tuk', '24'], ['3', 'john', '32']]


In [161]:
# regular expression

import re 
text = "a duck walk into a bar"
result = re.search("duck", text)
print(result)

<re.Match object; span=(2, 6), match='duck'>


In [162]:
# regular expression
import re 
text = "a duck walk into a bar"
result = re.search("duck", text) # True, False

if result:
    print("Duck Found")
else:
    print("Duck Not Found")

Duck Found


In [163]:
import re 
text = "a duck walk into a bar"
re.search("duck", text)[0]

'duck'

In [164]:
# regular expression
# import re 
from re import search 
text = "a duck walk into a bar"
search("duck", text)

<re.Match object; span=(2, 6), match='duck'>

In [165]:
# list comprehension -> 
numbers = [1,2,3,4,5] 


In [166]:
# Original list
result = []
for num in numbers:
    result.append(num*2)
print(result)


[2, 4, 6, 8, 10]


In [167]:
# Modern List
result = [ num*2 for num in numbers]
print(result)

[2, 4, 6, 8, 10]


In [168]:
# if we want only even number
even_nums = []

for num in numbers:
    if num % 2 == 0:
        even_nums.append(num)
print(even_nums)


[2, 4]


In [169]:
# if we want only odd number
odd_nums = []

for num in numbers:
    if num % 2 == 1:
        odd_nums.append(num)
print(odd_nums)

[1, 3, 5]


In [170]:
# the easy way 
even_nums = [num for num in numbers if num % 2 == 0]
odd_nums = [num for num in numbers if num % 2 == 1]

print(even_nums, odd_nums)

[2, 4] [1, 3, 5]


In [171]:
## json 
!ls *.json


newjsonfile.json  tuk.json


In [172]:
import json

with open("tuk.json", "r") as file:
    data = json.load(file)

In [173]:
data

{'name': 'tuk',
 'age': '24',
 'movie_lover': True,
 'movies': ['batman', 'superman']}

In [174]:
data["movies"][0]

'batman'

In [175]:
# create new .json file
school = {
    "name": "bootcamp",
    "batch": 7,
    "duration": "4 months"
}

with open("newjsonfile.json", "w") as file:
    json.dump(school, file)

In [176]:
!cat newjsonfile.json

{"name": "bootcamp", "batch": 7, "duration": "4 months"}

In [177]:
with open("newjsonfile.json", "r") as file:
    data2 = json.load(file)
data2

{'name': 'bootcamp', 'batch': 7, 'duration': '4 months'}

In [178]:
# API get request
import requests

url = "https://swapi.dev/api/people/1"

result = requests.get(url)

data_json = result.json()
data_json["name"]

'Luke Skywalker'

In [179]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [180]:
# char 1-5
from requests import get 

nums = list(range(1,6))

result = []

for i in nums:
    url = f"https://swapi.dev/api/people/{i}" 
    response = get(url)
    data = response.json()
    print(data["name"])

Luke Skywalker
C-3PO
R2-D2
Darth Vader
Leia Organa


In [181]:
# char 1-10
from requests import get #คือการ import แค่ฟังก์ชั่นเดียว 

nums = list(range(1,11))

result = []

for i in nums:
    url = f"https://swapi.dev/api/people/{i}" 
    response = get(url)
    data = response.json()
    row = [
        data["name"],
        data["height"],
        data["mass"],
        data["gender"]
    ]
    result.append(row)

print(result)


[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a'], ['Darth Vader', '202', '136', 'male'], ['Leia Organa', '150', '49', 'female'], ['Owen Lars', '178', '120', 'male'], ['Beru Whitesun lars', '165', '75', 'female'], ['R5-D4', '97', '32', 'n/a'], ['Biggs Darklighter', '183', '84', 'male'], ['Obi-Wan Kenobi', '182', '77', 'male']]


In [182]:
from requests import get 
from time import sleep

nums = list(range(1,11))

result = []

for i in nums:
    url = f"https://swapi.dev/api/people/{i}" 
    response = get(url)
    data = response.json()
    row = [
        data["name"],
        data["height"],
        data["mass"],
        data["gender"]
    ]
    result.append(row)
    print(result)
    sleep(1) #second



[['Luke Skywalker', '172', '77', 'male']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a'], ['Darth Vader', '202', '136', 'male']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a'], ['Darth Vader', '202', '136', 'male'], ['Leia Organa', '150', '49', 'female']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a'], ['Darth Vader', '202', '136', 'male'], ['Leia Organa', '150', '49', 'female'], ['Owen Lars', '178', '120', 'male']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a'], ['Darth Vader', '202', '136', 'male'], ['Leia Organa', '150', '49', 'female'], ['Owen Lars', '178', '120', 'male'], ['Beru Whitesun lars

In [183]:
import pandas as pd
df = pd.DataFrame(result, columns= ["name", "height", "mass", "gender"])
df

name height mass  gender
0      Luke Skywalker    172   77    male
1               C-3PO    167   75     n/a
2               R2-D2     96   32     n/a
3         Darth Vader    202  136    male
4         Leia Organa    150   49  female
5           Owen Lars    178  120    male
6  Beru Whitesun lars    165   75  female
7               R5-D4     97   32     n/a
8   Biggs Darklighter    183   84    male
9      Obi-Wan Kenobi    182   77    male

In [184]:
df.to_csv("starwarapi.csv")

## Web scraping ##

In [185]:
# web scraping
# gazpacho

In [186]:
!pip list

Package                       Version
----------------------------- ---------------------
absl-py                       1.4.0
alabaster                     0.7.13
albumentations                1.2.1
altair                        4.2.2
anyio                         3.6.2
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
array-record                  0.2.0
arviz                         0.15.1
astropy                       5.2.2
astunparse                    1.6.3
attrs                         23.1.0
audioread                     3.0.0
autograd                      1.5
Babel                         2.12.1
backcall                      0.2.0
beautifulsoup4                4.11.2
bleach                        6.0.0
blis                          0.7.9
blosc2                        2.0.0
bokeh                         2.4.3
branca                        0.6.0
build                         0.10.0
CacheControl                  0.12.11
ca

In [187]:
!pip install gazpacho

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [188]:
!pip list | grep "gaz"

gazpacho                      1.1


In [189]:
# !pip list | grep "^p"
# !pip list | grep "^b"

In [190]:
from gazpacho import Soup
from requests import get

url = "https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"

headers = {"Accept-Language": "en-US"}

response = get(url, headers = headers)

imdb = Soup(response.text)

In [191]:
type(imdb)

gazpacho.soup.Soup

In [192]:
imdb.find("title")

[<title>IMDb &quot;Top 100&quot;
 (Sorted by IMDb Rating Descending) - IMDb</title>,
 <title>IMDb, an Amazon company</title>]

In [193]:
imdb.find("title")[0]

<title>IMDb &quot;Top 100&quot;
(Sorted by IMDb Rating Descending) - IMDb</title>

In [194]:
imdb.find("title")[0].strip()

'IMDb "Top 100" (Sorted by IMDb Rating Descending) - IMDb'

In [195]:
#imdb.find("h3")

In [196]:
imdb.find("h3")[9].strip()

'10. Fight Club (1999)'

In [197]:
title_list = imdb.find("h3", {"class": "lister-item-header"})

In [198]:
for title in title_list:
    print(title.strip())

1. The Shawshank Redemption (1994)
2. The Godfather (1972)
3. The Dark Knight (2008)
4. Schindler's List (1993)
5. The Godfather Part II (1974)
6. 12 Angry Men (1957)
7. The Lord of the Rings: The Return of the King (2003)
8. Pulp Fiction (1994)
9. Inception (2010)
10. Fight Club (1999)
11. The Lord of the Rings: The Fellowship of the Ring (2001)
12. Forrest Gump (1994)
13. The Good, the Bad and the Ugly (1966)
14. The Lord of the Rings: The Two Towers (2002)
15. Interstellar (2014)
16. Goodfellas (1990)
17. The Matrix (1999)
18. One Flew Over the Cuckoo's Nest (1975)
19. Star Wars: Episode V - The Empire Strikes Back (1980)
20. The Green Mile (1999)
21. Se7en (1995)
22. The Silence of the Lambs (1991)
23. Star Wars: Episode IV - A New Hope (1977)
24. Saving Private Ryan (1998)
25. Spirited Away (2001)
26. Terminator 2: Judgment Day (1991)
27. City of God (2002)
28. Life Is Beautiful (1997)
29. Seven Samurai (1954)
30. It's a Wonderful Life (1946)
31. Harakiri (1962)
32. Parasite (2019

In [199]:
titles = [title.strip() for title in title_list]
print(titles)

['1. The Shawshank Redemption (1994)', '2. The Godfather (1972)', '3. The Dark Knight (2008)', "4. Schindler's List (1993)", '5. The Godfather Part II (1974)', '6. 12 Angry Men (1957)', '7. The Lord of the Rings: The Return of the King (2003)', '8. Pulp Fiction (1994)', '9. Inception (2010)', '10. Fight Club (1999)', '11. The Lord of the Rings: The Fellowship of the Ring (2001)', '12. Forrest Gump (1994)', '13. The Good, the Bad and the Ugly (1966)', '14. The Lord of the Rings: The Two Towers (2002)', '15. Interstellar (2014)', '16. Goodfellas (1990)', '17. The Matrix (1999)', "18. One Flew Over the Cuckoo's Nest (1975)", '19. Star Wars: Episode V - The Empire Strikes Back (1980)', '20. The Green Mile (1999)', '21. Se7en (1995)', '22. The Silence of the Lambs (1991)', '23. Star Wars: Episode IV - A New Hope (1977)', '24. Saving Private Ryan (1998)', '25. Spirited Away (2001)', '26. Terminator 2: Judgment Day (1991)', '27. City of God (2002)', '28. Life Is Beautiful (1997)', '29. Seven 

In [200]:
runtimes = imdb.find("span", {"class": "runtime"})
runtimes = [runtime.strip() for runtime in runtimes]
print(runtimes)

['142 min', '175 min', '152 min', '195 min', '202 min', '96 min', '201 min', '154 min', '148 min', '139 min', '178 min', '142 min', '178 min', '179 min', '169 min', '145 min', '136 min', '133 min', '124 min', '189 min', '127 min', '118 min', '121 min', '169 min', '125 min', '137 min', '130 min', '116 min', '207 min', '130 min', '133 min', '132 min', '151 min', '106 min', '110 min', '116 min', '155 min', '130 min', '117 min', '102 min', '88 min', '119 min', '150 min', '106 min', '109 min', '112 min', '165 min', '89 min', '112 min', '155 min']


In [201]:
import pandas as pd

df = pd.DataFrame({
    "title": titles,
    "runtime": runtimes
})
df.head()


title  runtime
0  1. The Shawshank Redemption (1994)  142 min
1             2. The Godfather (1972)  175 min
2           3. The Dark Knight (2008)  152 min
3          4. Schindler's List (1993)  195 min
4     5. The Godfather Part II (1974)  202 min

In [202]:
df.to_csv("imdb_data.csv")

# Basic Data tools

- numpy
- pandas
- sklearn

In [203]:
# numpy => numerical python
import numpy as np

num = [1,2,3,4,5]

# print(num*2) = [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

num_arr = np.array(num)
print(num_arr * 2, num_arr + 2)

[ 2  4  6  8 10] [3 4 5 6 7]


In [204]:
# statistical basic calculation
np.sum(num_arr) # equal to num_arr.sum() 
np.mean(num_arr)
np.median(num_arr) # but only num_arr.median() is error
np.std(num_arr)
np.min(num_arr)
np.max(num_arr)
len(num_arr)

5

In [205]:
# matrix, in python call 2D-array
m1 = np.array([
    [1,2],
    [3,4]
])
print(m1, "\n"*2, m1*5)

[[1 2]
 [3 4]] 

 [[ 5 10]
 [15 20]]


In [206]:
m2 = np.array([
    [5,5],
    [4, 2]
])

In [207]:
print(m1,"\n"*2,m2) # \n is new line, \n*2 double line

[[1 2]
 [3 4]] 

 [[5 5]
 [4 2]]


In [208]:
m1.dot(m2) # = np.dot(m1,m2)

array([[13,  9],
       [31, 23]])

In [209]:
 # intro to pandas

import pandas as pd
import numpy as np

In [210]:
hotel = pd.read_csv("Hotel.csv")
hotel

id       hotel location  price
0   1       Accor  Thiland     50
1   2        Lbis    Italy     50
2   3      London       UK     35
3   4       Seoul    Korea     30
4   5  Le Concord      USA     25

In [211]:
hotel.shape 

(5, 4)

In [212]:
hotel.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        5 non-null      int64 
 1   hotel     5 non-null      object
 2   location  5 non-null      object
 3   price     5 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes


In [213]:
hotel.describe()

id      price
count  5.000000   5.000000
mean   3.000000  38.000000
std    1.581139  11.510864
min    1.000000  25.000000
25%    2.000000  30.000000
50%    3.000000  35.000000
75%    4.000000  50.000000
max    5.000000  50.000000

In [214]:
hotel.describe(include = "all") 

id  hotel location      price
count   5.000000      5        5   5.000000
unique       NaN      5        5        NaN
top          NaN  Accor  Thiland        NaN
freq         NaN      1        1        NaN
mean    3.000000    NaN      NaN  38.000000
std     1.581139    NaN      NaN  11.510864
min     1.000000    NaN      NaN  25.000000
25%     2.000000    NaN      NaN  30.000000
50%     3.000000    NaN      NaN  35.000000
75%     4.000000    NaN      NaN  50.000000
max     5.000000    NaN      NaN  50.000000

In [215]:
hotel["hotel"]

0         Accor
1          Lbis
2        London
3         Seoul
4    Le Concord
Name: hotel, dtype: object

In [216]:
hotel.hotel

0         Accor
1          Lbis
2        London
3         Seoul
4    Le Concord
Name: hotel, dtype: object

In [217]:
# create new col
hotel["vat"] = hotel["price"] * 0.07
hotel

id       hotel location  price   vat
0   1       Accor  Thiland     50  3.50
1   2        Lbis    Italy     50  3.50
2   3      London       UK     35  2.45
3   4       Seoul    Korea     30  2.10
4   5  Le Concord      USA     25  1.75

In [218]:
# query (filter rows)
hotel.query("price > 40")

id  hotel location  price  vat
0   1  Accor  Thiland     50  3.5
1   2   Lbis    Italy     50  3.5

In [219]:
value_hotel = hotel.query("price > 40")
value_hotel.to_csv("value_hotel.csv")

In [220]:
# drop col
# axis 0 = drop row, 1 = col 
new_hotel = hotel.drop(["vat"], axis = 1)
new_hotel

id       hotel location  price
0   1       Accor  Thiland     50
1   2        Lbis    Italy     50
2   3      London       UK     35
3   4       Seoul    Korea     30
4   5  Le Concord      USA     25

In [221]:
hotel

id       hotel location  price   vat
0   1       Accor  Thiland     50  3.50
1   2        Lbis    Italy     50  3.50
2   3      London       UK     35  2.45
3   4       Seoul    Korea     30  2.10
4   5  Le Concord      USA     25  1.75

In [222]:
# inplace 
hotel.drop("vat", axis = 1, inplace= True)
hotel

id       hotel location  price
0   1       Accor  Thiland     50
1   2        Lbis    Italy     50
2   3      London       UK     35
3   4       Seoul    Korea     30
4   5  Le Concord      USA     25

In [223]:
# filter more than 1 condition
hotel.query(" price < 40 and location == 'UK' ")

id   hotel location  price
2   3  London       UK     35

In [224]:
# skelearn => machine learning most poplular python
# template in sklearn to train_test_split

In [225]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import pandas as pd


In [226]:
mtcars = pd.read_csv("https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv")

In [227]:
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [228]:
X = mtcars[["hp", "wt", "am"] ]
y = mtcars["mpg"]

In [229]:
# split data 80% train, 20% test
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.2, random_state= 42)

In [230]:
# train model
# model = LinearRegression()
## model = DecisionTreeRegressor()
model = RandomForestRegressor()
model.fit(X_train, y_train)

# test model/ scoring
pred = model.predict(X_test)

# MAE mean absolute error
mae = np.mean(np.absolute((y_test - pred)))

# MSE mean square error
mse = np.mean((y_test - pred) **2)

print(mae, mse)

2.140571428571426 9.485445714285676
